### ISSUE TITLE
meta description: Leading image in the post will blow it up

### ISSUE THREAD

**Issue by paulirish** [imathis/octopress#1082]
The top of my post looks like this

``` yaml

---
layout: post
title: "WebKit for Developers"
date: 2013-02-28 02:53
comments: true
description: "Let's try to answer some questions: What is WebKit? What isn't WebKit? How is WebKit used by WebKit-based browsers? Why are all WebKits not the same?"
categories:
  - front-end development
  - chrome

---


<img src="http://paulirish.com/assets/webkit-box.png" alt="WebKit box logo" style="border: 0;
margin: 0;
box-shadow: none;
float: right;
vertical-align: top;" >
For many of us developers, **WebKit is a black box**. We throw HTML, CSS, JS and a bunch of assets at it, and WebKit, somehow.. magically, gives us a webpage that looks and works well.  But in fact, [as my colleague Ilya Grigorik puts it](http://www.youtube.com/watch?v=kiPe7DPmEgE)...
```

The meta description generated by octopress used that multiline img tag, which doesn't work out so well:

``` html
  <meta name="description" content="<img src="http://paulirish.com/assets/webkit-box.png" alt="WebKit box logo" style="border: 0;
margin: 0;
box-shadow: none;
float: right;
vertical- &hellip;">
```
