### ISSUE TITLE
Can't get rid of collapsed sidebar horizontal line

### ISSUE THREAD

**Issue by kbrede** [imathis/octopress#1332]
![screens](https://f.cloud.github.com/assets/5295709/1017107/0b18e57a-0c09-11e3-895b-8404e81b7c8b.png)

In _config.yml I changed:

``` yaml
default_asides: [ ]
sidebar: collapse
```

In `sass/custom/_colors.scss` I added:

``` scss
html {
  background: #fff !important;
}
body {
  > div {
    background: #fff !important;
    > div {
      background: #fff !important;
      }
  }
}

$main-bg: #ffffff !default;
$page-bg: #ffffff !default;

// change header
$header-bg: #fff;
$title-color: #000000 !default;
$text-color: #333 !default;
$text-color-light: #777 !default;
$subtitle-color: darken($header-bg, 58);

// change navigation
$nav-bg: #fff;
$nav-bg-front: #fff;
$nav-bg-back: #fff;
$nav-color: darken($nav-bg, 78) !default;
$nav-color-hover: darken($nav-color, 25) !default;
$nav-border: darken($nav-bg, 50) !default;
$nav-border-top: darken($nav-bg, 33) !default;
$nav-border-bottom: darken($nav-bg, 33) !default;
$nav-border-left: darken($nav-bg, 11) !default;
$nav-border-right: lighten($nav-bg, 7) !default;

// change the footer
$footer-bg: #fff !default;
$footer-bg-back: #fff !default;
$footer-color: darken($footer-bg, 38) !default;
$footer-color-hover: darken($footer-color, 10) !default;
$footer-border-top: lighten($footer-bg, 15) !default;
$footer-border-bottom: darken($footer-bg, 15) !default;
$footer-link-color: darken($footer-bg, 38) !default;
$footer-link-color-hover: darken($footer-color, 25) !default;
$page-border-bottom: darken($footer-bg, 5) !default;
```

That gets me pretty much what I want but there's still a horizontal line on the right side of where the sidebar was.

I found both of these which appear to be the same issue I'm having.  I've tried all the fixes and none of them have worked for me.

https://github.com/imathis/octopress/issues/342
https://github.com/imathis/octopress/issues/118

I obtained the source today from git://github.com/imathis/octopress.git

Anyone know how I can get rid of this horizontal line?
Thanks,
Kent
