### ISSUE TITLE
Translating Octopress

### ISSUE THREAD

**Issue by Cycymomo** [imathis/octopress#1410]
Hi there !

I'm a french blogger and I decided to translate my Octopress blog into my own language. So I implemented a simple trick in order to do that.

:warning: This is not a multilingual site translation proposition. Only one language will be available after compile time :warning: 

`_config.yml` file:

```
# Put "&default" in front of your dictionary

fr: &default
  comments: Commentaires
  next_post: Article suivant
  prev_post: Article précédent
# etc ...

en:
  comments: Comments
  next_post: Next
  prev_post: Previous
# etc ...

# Don't touch it (the "*default" dictionary is copied into i18n)
i18n:
  <<: *default
```

So, instead of typing "Comments" in the core files, just use `{{site.i18n.comments}}` to use the correct translation at build time. Et voilà !

Hope it helps someone.

My commits are a little bit ... messy :) ('cause I "hard translated" in first place). But you can check my [`_config.yml` file](https://github.com/Nickdouille/sojavascript/blob/9f1bd87735b51a37e58807b50a5efe81c9e39dd8/_config.yml#L14) and look into [these](https://github.com/Nickdouille/sojavascript/commit/0aef8655457d39f2197d183be7bd8d83434d75a1) [commits](https://github.com/Nickdouille/sojavascript/commit/9f1bd87735b51a37e58807b50a5efe81c9e39dd8) to have an idea.

Thoughts ? Better ideas ?

n.b. sorry for my english
