### ISSUE TITLE
Conflict between Go Pygments syntax highlighting and inuit.css

### ISSUE THREAD

**Issue by dradtke** [imathis/octopress#1436]
I'm not sure if this is where this issue belongs, but I discovered a small conflict that causes Go-highlighted source code to exhibit weird behavior:

![go-syntax-error](https://f.cloud.github.com/assets/929204/1674479/f018794c-5cf9-11e3-9281-446c2d404416.png)

Notice the » character at the end of the source code. Inspecting the element in the browser shows that it's not part of the HTML, but I was finally able to track down the source in `sass/inuitcss/generic/_helper.scss`:

``` css
/**
 * Add a right-angled quote to links that imply movement, e.g.:
 *
   <a href=# class=go>Read more</a>
 *
 */
.go:after {
    content:"\00A0" "\00BB"!important;
}
```

The Go pygments lexer uses the CSS class `go` for syntax highlighting, which causes all Go source code to end in a right-angled quote. I was able to get the code to display normally by commenting out the above CSS in the resulting `stylesheets/screen.css`.

I know this isn't strictly an Octopress issue, but I wanted to bring this to the attention of anyone who may run into the same problem.
