### ISSUE TITLE
Optimize octopress theme for tablets

### ISSUE THREAD

**Issue by TheChymera** [imathis/octopress#1455]
I noticed that the default octopress theme scales quite acceptably on various display sizes. It does so via element size definitions like

```scss
@media only screen and (min-width: 768px) {
  margin-left: $pad-medium;
  margin-right: $pad-medium;
    }
```

which are found for instance in ```/sass/base/_layout.scss```.

The problem with this comes when using ~HD tablets. These tablets have pixel counts comparable with those of monitors, but have considerably smaller displays (as measured in cm). So wile I might want a centered content blog to only take up ~50% of horizontal space on a 720p monitor, I might want it to take up ~90% of horizontal space on a 720p tablet to give my user a comparable visual experience.

How could we optimize scaling so that it takes the physical dimensions of the display in consideration? Apparently this [may not be possible](http://stackoverflow.com/questions/11263747/how-to-get-screens-physical-size-i-e-in-inches) directly, but maybe we can extrapolate whether the user is using a tablet some other way?
