### ISSUE TITLE
Include styling for print (i.e. print.css)

### ISSUE THREAD

**Issue by timecode** [imathis/octopress#1521]
I wanted to print an article (to pdf) the other day and noticed it looked awful.

So, for the odd occasion where you need to 'print' an article (or even an entire blog) and still have it render as nice as it appears on screen...

Add to `_includes/head.html` the line:

``` html
<link href="{{ root_url }}/stylesheets/print.css" media="print" rel="stylesheet" type="text/css">
```

... and add a css file `stylesheets/print.css` with the following contents:

``` css
@import url("screen.css");

/* Article printing */

body>header,
nav,
footer,
aside,
.toggle-sidebar,
.pagination
{
  display: none;
}

html,
body,
article,
#main,
#content
{
  background-color:#FFF;
  border-width:0px;
  margin: 0px;
  padding: 0px;
}
```

I think support for this should be required in theme creation instructions, so Octopress theme's cater for a print.css too.

Anyway, I can now render to 'print' just as beautifully as rendering to screen :-)
Roll into the next release?
