### ISSUE TITLE
can I have a toc on asides?

### ISSUE THREAD

**Issue by kongluoxing** [imathis/octopress#1692]
Make a toc on post view, even stick it on the top, would be helpful with long artickle, do you think so?

**Comment by sonal-keshav** [comment]
it is possible to add TOC to your long posts with `!TOC` in your post itself.
Don't forget to add the following to your _config.yml file
```
rdiscount: 
  extensions:
    - autolink
    - footnotes
    - smart
    - generate_toc
  toc_token: "!TOC"
```
