### ISSUE TITLE
Pagination is broken (Octopress 2)

### ISSUE THREAD

**Issue by nielsk** [imathis/octopress#1718]
```yml
_config.yml:
paginate: 10
paginate_path: "posts/:num"
```
If setting are set like this the older-links go to /n+1 and not /posts/n+1

If you set it like this:
```yml
_config.yml:
paginate: 10
paginate_path: "blog/posts/:num"
```
The older/newer-links are correct but the blog-index is empty when / is opened.
Bonus: page 2 has a newer-link that goes to /1 or /blog/posts/1 (depending on settings) but needs actually go to the /root_of_the_blog especially since the side for "1" doesn't get generated.

I didn't test yet Octopress 3 in that regard because the default-theme has no pagination…So it might be a problem there as well.
