### ISSUE TITLE
`octopress post`: generate a file in _posts/ with front matter

### ISSUE THREAD

**Issue by paulnicholson** [imathis/octopress#403]
``` yaml

---
layout: post
title: "#{title.gsub(/&/,'&amp;')}"
date: #{Time.now.strftime('%Y-%m-%d %H:%M')}
comments: true
categories: 

---
```
