### ISSUE TITLE
Prose.io compatibility

### ISSUE THREAD

**Issue by darvin** [imathis/octopress#943]
add to default `_config.yml`:

``` yaml
#prose.io settings
prose:
  rooturl: "source"
  metadata:
    "source/_posts": |
      layout: post
      title: "Title"
      comments: true
      categories: 
      published: true
      date: CURRENT_DATETIME
```
