### ISSUE TITLE
Namespace configurations

### ISSUE THREAD

**Issue by imathis** [imathis/octopress#960]
Each config should be namespaced in the yaml. For example, instead of:

```
# Pinboard link stream
pinboard_user: imathis
pinboard_count: 3
```

You would have:

```
# Pinboard link stream
pinboard:
  user: imathis
  count: 3
```

This will prevent plugins and themes from accidentlally overwriting each others variables, and they don't need awful underscore filed variable names either.

Note: this will require updates to the templates.
